global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-api'
    static_configs:
      - targets: ['auth-api:8080']

  - job_name: 'catalog-api'
    static_configs:
      - targets: ['catalog-api:8080']

  - job_name: 'orders-api'
    static_configs:
      - targets: ['orders-api:8080']

  - job_name: 'kitchen-api'
    static_configs:
      - targets: ['kitchen-api:8080']
