apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: b1tech/fasttechfoods-orders:v1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__PostgresString
              value: "Host=$(POSTGRES_HOST);Port=$(POSTGRES_PORT);Database=$(POSTGRES_DB_ORDERS);Username=$(POSTGRES_USER_ORDERS);Password=$(POSTGRES_PASSWORD_ORDERS)"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB_ORDERS
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB_ORDERS
            - name: POSTGRES_USER_ORDERS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER_ORDERS
            - name: POSTGRES_PASSWORD_ORDERS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD_ORDERS
            - name: RabbitMq__Host
              value: rabbitmq